apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: deviceregistrysvcapp-zbkd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deviceregistrysvcapp-zbkd
    app.kubernetes.io/part-of: device-registry-2
  name: deviceregistrysvcapp-zbkd
  namespace: susdas-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: deviceregistrysvcapp-zbkd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: deviceregistrysvcapp-zbkd
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:974cb327f52b3ebe42b00457891a76bf10ac68bf1e08eb6078b11f1abd760cd1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
