apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: deviceregistrysvcapp-zbkd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deviceregistrysvcapp-zbkd
    app.kubernetes.io/part-of: device-registry-2
  name: deviceregistrysvcapp-zbkd
  namespace: susdas-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: deviceregistrysvcapp-zbkd
    weight: 100
status: {}
