apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: deviceregistrysvcapp-zbkd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deviceregistrysvcapp-zbkd
    app.kubernetes.io/part-of: device-registry-2
  name: deviceregistrysvcapp-zbkd
  namespace: susdas-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: deviceregistrysvcapp-zbkd
status:
  loadBalancer: {}
